#base docker file 
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  docker-course:
    build: .
    # ports: remove ports beacuse nginx will listen and redirect requests
    #   - "3000:3000"
    environment:
      - PORT=3000
      
    links:
      - mongo
    depends_on: # because this contaier depends on these list , containers in the list will run first
      - mongo 
  mongo:
    image: mongo #pull mongo image from docker hub
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=ibrahim 
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    # ports:
    #   - 27017:27017
    volumes: 
      - mongo-db:/data/db #name volume , to save data when down docker, mongo-db name from global  base docker compose volumes  
  redis:
    image: redis
volumes: #global colums used in other services
  mongo-db: #mongo db volum to not be prune when use docker volume/system prune