version: "3"
services:
  nginx:    
    ports:
      - "3000:80"
  docker-course:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=secret
      - MONGO_USER=ibrahim
      - MONGO_PASSWORD=123456789
    command: npm run dev
# docker compose file for development enviroment
